// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelBooking = `-- name: CancelBooking :execrows
UPDATE bookings 
SET status = 'cancelled', updated_at = NOW() 
WHERE id = $1 AND user_id = $2 AND status = 'pending'
`

type CancelBookingParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) CancelBooking(ctx context.Context, arg CancelBookingParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelBooking, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (
    user_id, status, total_amount, booking_reference, 
    payment_status, created_at, updated_at
) VALUES (
    $1, 'pending', $2, $3, 'pending', NOW(), NOW()
)
RETURNING id, user_id, status, total_amount, booking_reference, payment_status, created_at, updated_at
`

type CreateBookingParams struct {
	UserID           pgtype.UUID    `json:"user_id"`
	TotalAmount      pgtype.Numeric `json:"total_amount"`
	BookingReference string         `json:"booking_reference"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking, arg.UserID, arg.TotalAmount, arg.BookingReference)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalAmount,
		&i.BookingReference,
		&i.PaymentStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBookingFlight = `-- name: CreateBookingFlight :one
INSERT INTO booking_flights (booking_id, flight_id, flight_type, created_at)
VALUES ($1, $2, $3, NOW())
RETURNING id, booking_id, flight_id, flight_type
`

type CreateBookingFlightParams struct {
	BookingID  pgtype.UUID `json:"booking_id"`
	FlightID   pgtype.UUID `json:"flight_id"`
	FlightType string      `json:"flight_type"`
}

type CreateBookingFlightRow struct {
	ID         pgtype.UUID `json:"id"`
	BookingID  pgtype.UUID `json:"booking_id"`
	FlightID   pgtype.UUID `json:"flight_id"`
	FlightType string      `json:"flight_type"`
}

func (q *Queries) CreateBookingFlight(ctx context.Context, arg CreateBookingFlightParams) (CreateBookingFlightRow, error) {
	row := q.db.QueryRow(ctx, createBookingFlight, arg.BookingID, arg.FlightID, arg.FlightType)
	var i CreateBookingFlightRow
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.FlightID,
		&i.FlightType,
	)
	return i, err
}

const createPassenger = `-- name: CreatePassenger :one
INSERT INTO passengers (
    booking_id, first_name, last_name, email, 
    phone, date_of_birth, passport_number, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
RETURNING id, booking_id, first_name, last_name, email, phone, date_of_birth, passport_number, created_at
`

type CreatePassengerParams struct {
	BookingID      pgtype.UUID `json:"booking_id"`
	FirstName      string      `json:"first_name"`
	LastName       string      `json:"last_name"`
	Email          pgtype.Text `json:"email"`
	Phone          pgtype.Text `json:"phone"`
	DateOfBirth    pgtype.Date `json:"date_of_birth"`
	PassportNumber pgtype.Text `json:"passport_number"`
}

func (q *Queries) CreatePassenger(ctx context.Context, arg CreatePassengerParams) (Passenger, error) {
	row := q.db.QueryRow(ctx, createPassenger,
		arg.BookingID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.DateOfBirth,
		arg.PassportNumber,
	)
	var i Passenger
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.DateOfBirth,
		&i.PassportNumber,
		&i.CreatedAt,
	)
	return i, err
}

const createPassengerSeat = `-- name: CreatePassengerSeat :exec
INSERT INTO passenger_seats (passenger_id, seat_id, created_at)
VALUES ($1, $2, NOW())
`

type CreatePassengerSeatParams struct {
	PassengerID pgtype.UUID `json:"passenger_id"`
	SeatID      pgtype.UUID `json:"seat_id"`
}

func (q *Queries) CreatePassengerSeat(ctx context.Context, arg CreatePassengerSeatParams) error {
	_, err := q.db.Exec(ctx, createPassengerSeat, arg.PassengerID, arg.SeatID)
	return err
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT 
    b.id,
    b.user_id,
    b.status,
    b.total_amount,
    b.booking_reference,
    b.payment_status,
    b.created_at,
    b.updated_at,
    bf.flight_id,
    bf.flight_type,
    f.flight_number,
    f.airline_code,
    f.airline_name,
    f.departure_airport,
    f.arrival_airport,
    f.departure_time,
    f.arrival_time,
    f.duration
FROM bookings b
LEFT JOIN booking_flights bf ON b.id = bf.booking_id
LEFT JOIN flights f ON bf.flight_id = f.id
WHERE b.id = $1
`

type GetBookingByIDRow struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	Status           string             `json:"status"`
	TotalAmount      pgtype.Numeric     `json:"total_amount"`
	BookingReference string             `json:"booking_reference"`
	PaymentStatus    string             `json:"payment_status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	FlightID         pgtype.UUID        `json:"flight_id"`
	FlightType       pgtype.Text        `json:"flight_type"`
	FlightNumber     pgtype.Text        `json:"flight_number"`
	AirlineCode      pgtype.Text        `json:"airline_code"`
	AirlineName      pgtype.Text        `json:"airline_name"`
	DepartureAirport pgtype.Text        `json:"departure_airport"`
	ArrivalAirport   pgtype.Text        `json:"arrival_airport"`
	DepartureTime    pgtype.Timestamptz `json:"departure_time"`
	ArrivalTime      pgtype.Timestamptz `json:"arrival_time"`
	Duration         pgtype.Text        `json:"duration"`
}

func (q *Queries) GetBookingByID(ctx context.Context, id pgtype.UUID) (GetBookingByIDRow, error) {
	row := q.db.QueryRow(ctx, getBookingByID, id)
	var i GetBookingByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalAmount,
		&i.BookingReference,
		&i.PaymentStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FlightID,
		&i.FlightType,
		&i.FlightNumber,
		&i.AirlineCode,
		&i.AirlineName,
		&i.DepartureAirport,
		&i.ArrivalAirport,
		&i.DepartureTime,
		&i.ArrivalTime,
		&i.Duration,
	)
	return i, err
}

const getBookingPassengers = `-- name: GetBookingPassengers :many
SELECT 
    p.id,
    p.first_name,
    p.last_name,
    p.email,
    p.phone,
    p.date_of_birth,
    p.passport_number,
    ps.seat_id,
    s.seat_number
FROM passengers p
LEFT JOIN passenger_seats ps ON p.id = ps.passenger_id
LEFT JOIN seats s ON ps.seat_id = s.id
WHERE p.booking_id = $1
`

type GetBookingPassengersRow struct {
	ID             pgtype.UUID `json:"id"`
	FirstName      string      `json:"first_name"`
	LastName       string      `json:"last_name"`
	Email          pgtype.Text `json:"email"`
	Phone          pgtype.Text `json:"phone"`
	DateOfBirth    pgtype.Date `json:"date_of_birth"`
	PassportNumber pgtype.Text `json:"passport_number"`
	SeatID         pgtype.UUID `json:"seat_id"`
	SeatNumber     pgtype.Text `json:"seat_number"`
}

func (q *Queries) GetBookingPassengers(ctx context.Context, bookingID pgtype.UUID) ([]GetBookingPassengersRow, error) {
	rows, err := q.db.Query(ctx, getBookingPassengers, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBookingPassengersRow{}
	for rows.Next() {
		var i GetBookingPassengersRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.DateOfBirth,
			&i.PassportNumber,
			&i.SeatID,
			&i.SeatNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCabinClassByID = `-- name: GetCabinClassByID :one
SELECT id, flight_id, class_type, price, total_seats 
FROM cabin_classes 
WHERE id = $1
`

type GetCabinClassByIDRow struct {
	ID         pgtype.UUID    `json:"id"`
	FlightID   pgtype.UUID    `json:"flight_id"`
	ClassType  string         `json:"class_type"`
	Price      pgtype.Numeric `json:"price"`
	TotalSeats int32          `json:"total_seats"`
}

func (q *Queries) GetCabinClassByID(ctx context.Context, id pgtype.UUID) (GetCabinClassByIDRow, error) {
	row := q.db.QueryRow(ctx, getCabinClassByID, id)
	var i GetCabinClassByIDRow
	err := row.Scan(
		&i.ID,
		&i.FlightID,
		&i.ClassType,
		&i.Price,
		&i.TotalSeats,
	)
	return i, err
}

const getSeatByIDForUpdate = `-- name: GetSeatByIDForUpdate :one
SELECT id, flight_id, cabin_class_id, seat_number, status 
FROM seats 
WHERE id = $1 AND status = 'available'
FOR UPDATE
`

type GetSeatByIDForUpdateRow struct {
	ID           pgtype.UUID `json:"id"`
	FlightID     pgtype.UUID `json:"flight_id"`
	CabinClassID pgtype.UUID `json:"cabin_class_id"`
	SeatNumber   string      `json:"seat_number"`
	Status       string      `json:"status"`
}

func (q *Queries) GetSeatByIDForUpdate(ctx context.Context, id pgtype.UUID) (GetSeatByIDForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getSeatByIDForUpdate, id)
	var i GetSeatByIDForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.FlightID,
		&i.CabinClassID,
		&i.SeatNumber,
		&i.Status,
	)
	return i, err
}

const getUserBookings = `-- name: GetUserBookings :many
SELECT 
    b.id,
    b.user_id,
    b.status,
    b.total_amount,
    b.booking_reference,
    b.payment_status,
    b.created_at,
    b.updated_at,
    bf.flight_id,
    bf.flight_type,
    f.flight_number,
    f.airline_code,
    f.airline_name,
    f.departure_airport,
    f.arrival_airport,
    f.departure_time,
    f.arrival_time,
    f.duration,
    (
        SELECT cc.class_type
        FROM passengers p
        JOIN passenger_seats ps ON p.id = ps.passenger_id
        JOIN seats s ON ps.seat_id = s.id
        JOIN cabin_classes cc ON s.cabin_class_id = cc.id
        WHERE p.booking_id = b.id
        LIMIT 1
    ) as cabin_class
FROM bookings b
LEFT JOIN booking_flights bf ON b.id = bf.booking_id
LEFT JOIN flights f ON bf.flight_id = f.id
WHERE b.user_id = $1
ORDER BY b.created_at DESC
`

type GetUserBookingsRow struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	Status           string             `json:"status"`
	TotalAmount      pgtype.Numeric     `json:"total_amount"`
	BookingReference string             `json:"booking_reference"`
	PaymentStatus    string             `json:"payment_status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	FlightID         pgtype.UUID        `json:"flight_id"`
	FlightType       pgtype.Text        `json:"flight_type"`
	FlightNumber     pgtype.Text        `json:"flight_number"`
	AirlineCode      pgtype.Text        `json:"airline_code"`
	AirlineName      pgtype.Text        `json:"airline_name"`
	DepartureAirport pgtype.Text        `json:"departure_airport"`
	ArrivalAirport   pgtype.Text        `json:"arrival_airport"`
	DepartureTime    pgtype.Timestamptz `json:"departure_time"`
	ArrivalTime      pgtype.Timestamptz `json:"arrival_time"`
	Duration         pgtype.Text        `json:"duration"`
	CabinClass       string             `json:"cabin_class"`
}

func (q *Queries) GetUserBookings(ctx context.Context, userID pgtype.UUID) ([]GetUserBookingsRow, error) {
	rows, err := q.db.Query(ctx, getUserBookings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserBookingsRow{}
	for rows.Next() {
		var i GetUserBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.TotalAmount,
			&i.BookingReference,
			&i.PaymentStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FlightID,
			&i.FlightType,
			&i.FlightNumber,
			&i.AirlineCode,
			&i.AirlineName,
			&i.DepartureAirport,
			&i.ArrivalAirport,
			&i.DepartureTime,
			&i.ArrivalTime,
			&i.Duration,
			&i.CabinClass,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseSeats = `-- name: ReleaseSeats :exec
UPDATE seats 
SET status = 'available' 
WHERE id IN (
    SELECT ps.seat_id 
    FROM passenger_seats ps
    JOIN passengers p ON ps.passenger_id = p.id
    WHERE p.booking_id = $1
)
`

func (q *Queries) ReleaseSeats(ctx context.Context, bookingID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, releaseSeats, bookingID)
	return err
}
