// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: flights.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFlight = `-- name: CreateFlight :one
INSERT INTO flights (flight_number, airline_code, airline_name, departure_airport, arrival_airport, departure_time, arrival_time, duration, amadeus_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, flight_number, airline_code, airline_name, departure_airport, arrival_airport, departure_time, arrival_time, duration, amadeus_id, wakanow_id, created_at, updated_at
`

type CreateFlightParams struct {
	FlightNumber     string             `json:"flight_number"`
	AirlineCode      string             `json:"airline_code"`
	AirlineName      pgtype.Text        `json:"airline_name"`
	DepartureAirport string             `json:"departure_airport"`
	ArrivalAirport   string             `json:"arrival_airport"`
	DepartureTime    pgtype.Timestamptz `json:"departure_time"`
	ArrivalTime      pgtype.Timestamptz `json:"arrival_time"`
	Duration         pgtype.Text        `json:"duration"`
	AmadeusID        pgtype.Text        `json:"amadeus_id"`
}

func (q *Queries) CreateFlight(ctx context.Context, arg CreateFlightParams) (Flight, error) {
	row := q.db.QueryRow(ctx, createFlight,
		arg.FlightNumber,
		arg.AirlineCode,
		arg.AirlineName,
		arg.DepartureAirport,
		arg.ArrivalAirport,
		arg.DepartureTime,
		arg.ArrivalTime,
		arg.Duration,
		arg.AmadeusID,
	)
	var i Flight
	err := row.Scan(
		&i.ID,
		&i.FlightNumber,
		&i.AirlineCode,
		&i.AirlineName,
		&i.DepartureAirport,
		&i.ArrivalAirport,
		&i.DepartureTime,
		&i.ArrivalTime,
		&i.Duration,
		&i.AmadeusID,
		&i.WakanowID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFlightByID = `-- name: GetFlightByID :one
SELECT id, flight_number, airline_code, airline_name, departure_airport, arrival_airport, departure_time, arrival_time, duration, amadeus_id, wakanow_id, created_at, updated_at FROM flights
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetFlightByID(ctx context.Context, id pgtype.UUID) (Flight, error) {
	row := q.db.QueryRow(ctx, getFlightByID, id)
	var i Flight
	err := row.Scan(
		&i.ID,
		&i.FlightNumber,
		&i.AirlineCode,
		&i.AirlineName,
		&i.DepartureAirport,
		&i.ArrivalAirport,
		&i.DepartureTime,
		&i.ArrivalTime,
		&i.Duration,
		&i.AmadeusID,
		&i.WakanowID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFlightsByRoute = `-- name: ListFlightsByRoute :many
SELECT id, flight_number, airline_code, airline_name, departure_airport, arrival_airport, departure_time, arrival_time, duration, amadeus_id, wakanow_id, created_at, updated_at FROM flights
WHERE departure_airport = $1 AND arrival_airport = $2
  AND departure_time >= $3 AND departure_time < $4
ORDER BY departure_time
`

type ListFlightsByRouteParams struct {
	DepartureAirport string             `json:"departure_airport"`
	ArrivalAirport   string             `json:"arrival_airport"`
	DepartureTime    pgtype.Timestamptz `json:"departure_time"`
	DepartureTime_2  pgtype.Timestamptz `json:"departure_time_2"`
}

func (q *Queries) ListFlightsByRoute(ctx context.Context, arg ListFlightsByRouteParams) ([]Flight, error) {
	rows, err := q.db.Query(ctx, listFlightsByRoute,
		arg.DepartureAirport,
		arg.ArrivalAirport,
		arg.DepartureTime,
		arg.DepartureTime_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Flight{}
	for rows.Next() {
		var i Flight
		if err := rows.Scan(
			&i.ID,
			&i.FlightNumber,
			&i.AirlineCode,
			&i.AirlineName,
			&i.DepartureAirport,
			&i.ArrivalAirport,
			&i.DepartureTime,
			&i.ArrivalTime,
			&i.Duration,
			&i.AmadeusID,
			&i.WakanowID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
