// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Booking struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	Status           string             `json:"status"`
	TotalAmount      pgtype.Numeric     `json:"total_amount"`
	BookingReference string             `json:"booking_reference"`
	PaymentStatus    string             `json:"payment_status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type BookingFlight struct {
	ID         pgtype.UUID        `json:"id"`
	BookingID  pgtype.UUID        `json:"booking_id"`
	FlightID   pgtype.UUID        `json:"flight_id"`
	FlightType string             `json:"flight_type"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type CabinClass struct {
	ID         pgtype.UUID        `json:"id"`
	FlightID   pgtype.UUID        `json:"flight_id"`
	ClassType  string             `json:"class_type"`
	Price      pgtype.Numeric     `json:"price"`
	TotalSeats int32              `json:"total_seats"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Flight struct {
	ID               pgtype.UUID        `json:"id"`
	FlightNumber     string             `json:"flight_number"`
	AirlineCode      string             `json:"airline_code"`
	AirlineName      pgtype.Text        `json:"airline_name"`
	DepartureAirport string             `json:"departure_airport"`
	ArrivalAirport   string             `json:"arrival_airport"`
	DepartureTime    pgtype.Timestamptz `json:"departure_time"`
	ArrivalTime      pgtype.Timestamptz `json:"arrival_time"`
	Duration         pgtype.Text        `json:"duration"`
	AmadeusID        pgtype.Text        `json:"amadeus_id"`
	WakanowID        pgtype.Text        `json:"wakanow_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Passenger struct {
	ID             pgtype.UUID        `json:"id"`
	BookingID      pgtype.UUID        `json:"booking_id"`
	FirstName      string             `json:"first_name"`
	LastName       string             `json:"last_name"`
	Email          pgtype.Text        `json:"email"`
	Phone          pgtype.Text        `json:"phone"`
	DateOfBirth    pgtype.Date        `json:"date_of_birth"`
	PassportNumber pgtype.Text        `json:"passport_number"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type PassengerSeat struct {
	ID          pgtype.UUID        `json:"id"`
	PassengerID pgtype.UUID        `json:"passenger_id"`
	SeatID      pgtype.UUID        `json:"seat_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Payment struct {
	ID                    pgtype.UUID        `json:"id"`
	BookingID             pgtype.UUID        `json:"booking_id"`
	StripePaymentIntentID string             `json:"stripe_payment_intent_id"`
	Amount                pgtype.Numeric     `json:"amount"`
	Currency              string             `json:"currency"`
	Status                string             `json:"status"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type Seat struct {
	ID           pgtype.UUID        `json:"id"`
	FlightID     pgtype.UUID        `json:"flight_id"`
	CabinClassID pgtype.UUID        `json:"cabin_class_id"`
	SeatNumber   string             `json:"seat_number"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                    pgtype.UUID        `json:"id"`
	Email                 string             `json:"email"`
	PasswordHash          string             `json:"password_hash"`
	FirstName             pgtype.Text        `json:"first_name"`
	LastName              pgtype.Text        `json:"last_name"`
	RefreshToken          pgtype.Text        `json:"refresh_token"`
	RefreshTokenExpiresAt pgtype.Timestamptz `json:"refresh_token_expires_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}
