// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ClearUserRefreshToken(ctx context.Context, id pgtype.UUID) error
	CreateFlight(ctx context.Context, arg CreateFlightParams) (Flight, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetAvailableSeatsByFlight(ctx context.Context, flightID pgtype.UUID) ([]GetAvailableSeatsByFlightRow, error)
	GetFlightByID(ctx context.Context, id pgtype.UUID) (Flight, error)
	GetSeatsByFlight(ctx context.Context, flightID pgtype.UUID) ([]GetSeatsByFlightRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListFlightsByRoute(ctx context.Context, arg ListFlightsByRouteParams) ([]Flight, error)
	UpdateSeatStatus(ctx context.Context, arg UpdateSeatStatusParams) error
	UpdateUserRefreshToken(ctx context.Context, arg UpdateUserRefreshTokenParams) error
}

var _ Querier = (*Queries)(nil)
