// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAvailableSeatsByFlight = `-- name: GetAvailableSeatsByFlight :many
SELECT s.id, s.flight_id, s.cabin_class_id, s.seat_number, s.status, s.created_at, cc.class_type, cc.price
FROM seats s
JOIN cabin_classes cc ON s.cabin_class_id = cc.id
WHERE s.flight_id = $1 AND s.status = 'available'
ORDER BY s.seat_number
`

type GetAvailableSeatsByFlightRow struct {
	ID           pgtype.UUID        `json:"id"`
	FlightID     pgtype.UUID        `json:"flight_id"`
	CabinClassID pgtype.UUID        `json:"cabin_class_id"`
	SeatNumber   string             `json:"seat_number"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ClassType    string             `json:"class_type"`
	Price        pgtype.Numeric     `json:"price"`
}

func (q *Queries) GetAvailableSeatsByFlight(ctx context.Context, flightID pgtype.UUID) ([]GetAvailableSeatsByFlightRow, error) {
	rows, err := q.db.Query(ctx, getAvailableSeatsByFlight, flightID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAvailableSeatsByFlightRow{}
	for rows.Next() {
		var i GetAvailableSeatsByFlightRow
		if err := rows.Scan(
			&i.ID,
			&i.FlightID,
			&i.CabinClassID,
			&i.SeatNumber,
			&i.Status,
			&i.CreatedAt,
			&i.ClassType,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeatsByFlight = `-- name: GetSeatsByFlight :many
SELECT s.id, s.flight_id, s.cabin_class_id, s.seat_number, s.status, s.created_at, cc.class_type, cc.price
FROM seats s
JOIN cabin_classes cc ON s.cabin_class_id = cc.id
WHERE s.flight_id = $1
ORDER BY s.seat_number
`

type GetSeatsByFlightRow struct {
	ID           pgtype.UUID        `json:"id"`
	FlightID     pgtype.UUID        `json:"flight_id"`
	CabinClassID pgtype.UUID        `json:"cabin_class_id"`
	SeatNumber   string             `json:"seat_number"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ClassType    string             `json:"class_type"`
	Price        pgtype.Numeric     `json:"price"`
}

func (q *Queries) GetSeatsByFlight(ctx context.Context, flightID pgtype.UUID) ([]GetSeatsByFlightRow, error) {
	rows, err := q.db.Query(ctx, getSeatsByFlight, flightID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSeatsByFlightRow{}
	for rows.Next() {
		var i GetSeatsByFlightRow
		if err := rows.Scan(
			&i.ID,
			&i.FlightID,
			&i.CabinClassID,
			&i.SeatNumber,
			&i.Status,
			&i.CreatedAt,
			&i.ClassType,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSeatStatus = `-- name: UpdateSeatStatus :exec
UPDATE seats
SET status = $2
WHERE id = $1
`

type UpdateSeatStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateSeatStatus(ctx context.Context, arg UpdateSeatStatusParams) error {
	_, err := q.db.Exec(ctx, updateSeatStatus, arg.ID, arg.Status)
	return err
}
